import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../core/dto/personalization_dto.dart';
import '../../game/providers/personalization_providers.dart';
import '../../game/providers/personalization_settings_provider.dart';

class PersonalizationSettingsScreen extends ConsumerWidget {
  final String playerId;

  const PersonalizationSettingsScreen({super.key, required this.playerId});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final enabled = ref.watch(personalizationEnabledProvider(playerId));
    final settings = ref.watch(personalizationSettingsProvider);
    final notifier = ref.read(personalizationSettingsProvider.notifier);

    return Scaffold(
      backgroundColor: const Color(0xFFF8FAFF),
      appBar: AppBar(
        backgroundColor: Colors.white,
        surfaceTintColor: Colors.transparent,
        elevation: 0.5,
        shadowColor: Colors.black12,
        title: const Text(
          'Personalization',
          style: TextStyle(
            fontSize: 17,
            fontWeight: FontWeight.w700,
            color: Color(0xFF1E293B),
          ),
        ),
        iconTheme: const IconThemeData(color: Color(0xFF1E293B)),
      ),
      body: ListView(
        padding: const EdgeInsets.symmetric(vertical: 16),
        children: [
          // ── Main toggle ───────────────────────────────────────────────────
          _SectionHeader(title: 'Recommendations'),
          _ToggleTile(
            icon: Icons.psychology_rounded,
            iconColor: const Color(0xFF6366F1),
            title: 'Adaptive Recommendations',
            subtitle: enabled
                ? 'Personalised content based on your play style'
                : 'Showing default experience',
            value: enabled,
            onChanged: (value) => _toggleEnabled(ref, value),
          ),

          if (enabled) ...[
            const SizedBox(height: 8),

            // ── Display preferences ───────────────────────────────────────
            _SectionHeader(title: 'Display Preferences'),
            _ToggleTile(
              icon: Icons.filter_list_rounded,
              iconColor: const Color(0xFF10B981),
              title: 'Reduce suggestions',
              subtitle: 'Show at most 2 recommendation cards at a time',
              value: settings.reduceSuggestions,
              onChanged: notifier.setReduceSuggestions,
            ),
            _ToggleTile(
              icon: Icons.help_outline_rounded,
              iconColor: const Color(0xFF64B5F6),
              title: 'Show recommendation reasons',
              subtitle: 'Display "Why am I seeing this?" below each card',
              value: settings.showReasons,
              onChanged: notifier.setShowReasons,
            ),

            const SizedBox(height: 8),

            // ── Reset ─────────────────────────────────────────────────────
            _SectionHeader(title: 'Data'),
            _ActionTile(
              icon: Icons.restart_alt_rounded,
              iconColor: const Color(0xFFF59E0B),
              title: 'Reset recommendations',
              subtitle: 'Clears local preference history — takes effect next session',
              onTap: () => _resetRecommendations(context, ref),
            ),
          ],

          const SizedBox(height: 24),

          // ── Info footer ───────────────────────────────────────────────────
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 20),
            child: Text(
              'Recommendations are generated by Synaptix based on your gameplay '
              'activity. They are designed to be helpful, not intrusive. '
              'You can turn them off at any time.',
              style: TextStyle(
                fontSize: 12,
                color: Colors.grey.shade500,
                height: 1.5,
              ),
              textAlign: TextAlign.center,
            ),
          ),
        ],
      ),
    );
  }

  Future<void> _toggleEnabled(WidgetRef ref, bool value) async {
    try {
      final newState = await ref
          .read(personalizationServiceProvider)
          .togglePersonalization(playerId: playerId, enabled: value);
      ref.read(personalizationEnabledProvider(playerId).notifier).state =
          newState;
    } catch (_) {
      // Optimistic update — revert silently on failure.
      ref.read(personalizationEnabledProvider(playerId).notifier).state =
          !value;
    }
  }

  void _resetRecommendations(BuildContext context, WidgetRef ref) {
    ref.read(personalizationServiceProvider).fireEvent(
          playerId,
          BehaviourEventDto(
            eventType: 'recommendation_reset',
            eventSource: 'settings',
          ),
        );
    ref.invalidate(homePersonalizationProvider(playerId));
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(
        content: Text('Recommendation history cleared.'),
        behavior: SnackBarBehavior.floating,
      ),
    );
  }
}

// ── Private widgets ───────────────────────────────────────────────────────────

class _SectionHeader extends StatelessWidget {
  final String title;
  const _SectionHeader({required this.title});

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.fromLTRB(20, 8, 20, 6),
      child: Text(
        title.toUpperCase(),
        style: const TextStyle(
          fontSize: 11,
          fontWeight: FontWeight.w700,
          color: Color(0xFF94A3B8),
          letterSpacing: 0.8,
        ),
      ),
    );
  }
}

class _ToggleTile extends StatelessWidget {
  final IconData icon;
  final Color iconColor;
  final String title;
  final String subtitle;
  final bool value;
  final ValueChanged<bool> onChanged;

  const _ToggleTile({
    required this.icon,
    required this.iconColor,
    required this.title,
    required this.subtitle,
    required this.value,
    required this.onChanged,
  });

  @override
  Widget build(BuildContext context) {
    return Container(
      margin: const EdgeInsets.symmetric(horizontal: 16, vertical: 3),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(14),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.04),
            blurRadius: 6,
            offset: const Offset(0, 1),
          ),
        ],
      ),
      child: SwitchListTile(
        contentPadding: const EdgeInsets.fromLTRB(16, 4, 12, 4),
        secondary: Container(
          width: 36,
          height: 36,
          decoration: BoxDecoration(
            color: iconColor.withValues(alpha: 0.1),
            borderRadius: BorderRadius.circular(9),
          ),
          child: Icon(icon, color: iconColor, size: 18),
        ),
        title: Text(
          title,
          style: const TextStyle(
            fontSize: 14,
            fontWeight: FontWeight.w600,
            color: Color(0xFF1E293B),
          ),
        ),
        subtitle: Text(
          subtitle,
          style: const TextStyle(fontSize: 12, color: Color(0xFF64748B)),
        ),
        value: value,
        activeColor: const Color(0xFF6366F1),
        onChanged: onChanged,
      ),
    );
  }
}

class _ActionTile extends StatelessWidget {
  final IconData icon;
  final Color iconColor;
  final String title;
  final String subtitle;
  final VoidCallback onTap;

  const _ActionTile({
    required this.icon,
    required this.iconColor,
    required this.title,
    required this.subtitle,
    required this.onTap,
  });

  @override
  Widget build(BuildContext context) {
    return Container(
      margin: const EdgeInsets.symmetric(horizontal: 16, vertical: 3),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(14),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.04),
            blurRadius: 6,
            offset: const Offset(0, 1),
          ),
        ],
      ),
      child: ListTile(
        contentPadding: const EdgeInsets.fromLTRB(16, 4, 16, 4),
        leading: Container(
          width: 36,
          height: 36,
          decoration: BoxDecoration(
            color: iconColor.withValues(alpha: 0.1),
            borderRadius: BorderRadius.circular(9),
          ),
          child: Icon(icon, color: iconColor, size: 18),
        ),
        title: Text(
          title,
          style: const TextStyle(
            fontSize: 14,
            fontWeight: FontWeight.w600,
            color: Color(0xFF1E293B),
          ),
        ),
        subtitle: Text(
          subtitle,
          style: const TextStyle(fontSize: 12, color: Color(0xFF64748B)),
        ),
        onTap: onTap,
      ),
    );
  }
}
