import '../../game/models/admin_user_model.dart';

/// Fallback sample users for offline / unsupported backend environments.
List<AdminUserModel> getMockUsers() {
  return [
    AdminUserModel(
      id: '1',
      username: 'john_doe',
      email: 'john@example.com',
      status: UserStatus.online,
      role: UserRole.premium,
      ageGroup: AgeGroup.adult,
      createdAt: DateTime.now().subtract(const Duration(days: 30)),
      lastActive: DateTime.now().subtract(const Duration(minutes: 5)),
      totalGamesPlayed: 145,
      totalPoints: 12450,
      winRate: 0.68,
      isVerified: true,
    ),
    AdminUserModel(
      id: '2',
      username: 'jane_smith',
      email: 'jane@example.com',
      status: UserStatus.offline,
      role: UserRole.user,
      ageGroup: AgeGroup.teen,
      createdAt: DateTime.now().subtract(const Duration(days: 15)),
      lastActive: DateTime.now().subtract(const Duration(hours: 2)),
      totalGamesPlayed: 78,
      totalPoints: 5680,
      winRate: 0.54,
      isVerified: true,
    ),
    AdminUserModel(
      id: '3',
      username: 'bob_wilson',
      email: 'bob@example.com',
      status: UserStatus.away,
      role: UserRole.moderator,
      ageGroup: AgeGroup.adult,
      createdAt: DateTime.now().subtract(const Duration(days: 90)),
      lastActive: DateTime.now().subtract(const Duration(minutes: 30)),
      totalGamesPlayed: 423,
      totalPoints: 28900,
      winRate: 0.72,
      isVerified: true,
    ),
    AdminUserModel(
      id: '4',
      username: 'alice_brown',
      email: 'alice@example.com',
      status: UserStatus.online,
      role: UserRole.admin,
      ageGroup: AgeGroup.adult,
      createdAt: DateTime.now().subtract(const Duration(days: 180)),
      lastActive: DateTime.now(),
      totalGamesPlayed: 892,
      totalPoints: 56780,
      winRate: 0.85,
      isVerified: true,
    ),
    AdminUserModel(
      id: '5',
      username: 'charlie_davis',
      email: 'charlie@example.com',
      status: UserStatus.offline,
      role: UserRole.user,
      ageGroup: AgeGroup.child,
      createdAt: DateTime.now().subtract(const Duration(days: 7)),
      lastActive: DateTime.now().subtract(const Duration(days: 1)),
      totalGamesPlayed: 23,
      totalPoints: 1450,
      winRate: 0.41,
      isVerified: false,
    ),
    AdminUserModel(
      id: '6',
      username: 'banned_user',
      email: 'banned@example.com',
      status: UserStatus.offline,
      role: UserRole.user,
      ageGroup: AgeGroup.teen,
      createdAt: DateTime.now().subtract(const Duration(days: 60)),
      lastActive: DateTime.now().subtract(const Duration(days: 10)),
      totalGamesPlayed: 56,
      totalPoints: 2340,
      winRate: 0.32,
      isVerified: false,
      isBanned: true,
      banReason: 'Inappropriate behavior',
    ),
  ];
}
